flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

---

spring:
  profiles: data
flyway:
  locations: filesystem:src/main/resources/db/qa-migration
  ignoreMissingMigrations:liqu true



